---

- name: Download binary
  unarchive:
    src: https://github.com/bitly/oauth2_proxy/releases/download/v2.1/oauth2_proxy-2.1.linux-amd64.go1.6.tar.gz
    remote_src: yes
    dest: /home/ubuntu
    mode: u=rwx,g=rx,o=r
    owner: ubuntu
    group: ubuntu
  become: yes

- name: Install binary
  file:
    src: /home/ubuntu/oauth2_proxy-2.1.linux-amd64.go1.6/oauth2_proxy
    dest: /usr/local/bin/oauth2_proxy
    state: link
    mode: u=rwx,g=rx,o=r
    owner: ubuntu
    group: ubuntu
  become: yes
